### ISSUE TITLE
above version 2.8.0.0 didnt make wallet.dat file itself.

### ISSUE THREAD

**Issue by future-guard** [pepeteam/pepecoin#32]
I use ubuntu 16.04

It crash when pepecoind start.

************************
EXCEPTION: NSt8ios_base7failureB5cxx11E
CDataStream::read() : end of data: iostream error
pepecoin in AppInit()

terminate called after throwing an instance of 'std::ios_base::failure[abi:cxx11]'
  what():  CDataStream::read() : end of data: iostream error
Aborted (core dumped)

**Comment by damoos3** [comment]
temp fix you can create .pepecoin folder that error happens when theres no datadir. One dev mentioned he found out why it happens. 

you can in the meanwhile make the data dir for pepecoind by doing

mk .pepecoin in the home or root folder

**Comment by damoos3** [comment]
Heres what a dev had to say about it


"I had to run it through gdb with thread debugging and isolated it.

It's happening when it loads the block index. Something changed maybe a leveldb dependency or something, but on first load its returning a valid db cursor that isnt pointing to anything because no records yet, whereas before the check on that would detect it.  Pivx added an exception check in the same place.

I fixed it locally just havent pushed any code."

It will be pushed out soon until then. you can 

mkdir .pepecoin and use the snapshot provided on the seed directory

http://seed2.pepecoin.co/memetic-pepecoin-chainsync-12-01-2018.tar


recommend you stop by t.me/pepecoins too for live chat community and im always there to help out

**Comment by jki123** [comment]
Thanks for the reply, it's running fine now.

**Comment by damoos3** [comment]
glad i could help,
that fix i recommended is a manual fix soon there will be a commit in the repo correcting future downloads

**Comment by cyberpepe** [comment]
> glad i could help,
> that fix i recommended is a manual fix soon there will be a commit in the repo correcting future downloads

when

**Comment by projectmemetic** [comment]
Now

**Comment by cyberpepe** [comment]
Fixed in 2.8.0.1
